import { DEMO_USER_ID } from "@/lib/config";
import type {
  Game,
  GameImportInput,
  GamePriceSnapshot,
  PlayerCountSnapshot,
  PriceAlert,
  StoreOffer,
  User,
  WatchlistItem
} from "@/lib/types";

const baseDate = new Date("2026-06-18T12:00:00.000Z");
const dayMs = 24 * 60 * 60 * 1000;

function daysAgo(days: number): Date {
  return new Date(baseDate.getTime() - days * dayMs);
}

type GameFixture = Omit<Game, "createdAt" | "updatedAt" | "source"> & {
  basePrice: number;
  currentPrice: number;
  historicalLow: number;
  currentPlayers: number;
  trendFactor: number;
  stores: Array<{
    storeName: string;
    price: number;
    discountPercent: number;
    drm: string;
    isOfficial?: boolean;
  }>;
};

const fixtures: GameFixture[] = [
  {
    id: "counter-strike-2",
    steamAppId: 730,
    title: "Counter-Strike 2",
    slug: "counter-strike-2",
    platform: "Steam",
    description:
      "Competitive tactical shooter with a large esports ecosystem and a free-to-play model.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/730/header.jpg",
    genres: ["FPS", "Competitive", "Esports"],
    developer: "Valve",
    publisher: "Valve",
    releaseDate: "2023-09-27",
    reviewScore: 78,
    basePrice: 0,
    currentPrice: 0,
    historicalLow: 0,
    currentPlayers: 782000,
    trendFactor: 1.04,
    stores: [{ storeName: "Steam", price: 0, discountPercent: 0, drm: "Steam", isOfficial: true }]
  },
  {
    id: "cyberpunk-2077",
    steamAppId: 1091500,
    title: "Cyberpunk 2077",
    slug: "cyberpunk-2077",
    platform: "PC",
    description:
      "Open-world RPG set in Night City with branching quests, cyberware builds and cinematic storytelling.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/1091500/header.jpg",
    genres: ["RPG", "Open World", "Sci-fi"],
    developer: "CD PROJEKT RED",
    publisher: "CD PROJEKT RED",
    releaseDate: "2020-12-10",
    reviewScore: 83,
    basePrice: 199.99,
    currentPrice: 119.99,
    historicalLow: 79.99,
    currentPlayers: 48200,
    trendFactor: 1.11,
    stores: [
      { storeName: "Steam", price: 119.99, discountPercent: 40, drm: "Steam", isOfficial: true },
      { storeName: "GOG.com", price: 114.99, discountPercent: 43, drm: "DRM-free", isOfficial: true },
      { storeName: "Humble Store", price: 122.49, discountPercent: 39, drm: "Steam" }
    ]
  },
  {
    id: "the-witcher-3",
    steamAppId: 292030,
    title: "The Witcher 3: Wild Hunt",
    slug: "the-witcher-3",
    platform: "PC",
    description:
      "Story-driven fantasy RPG with a large open world, expansions and long-tail player interest.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/292030/header.jpg",
    genres: ["RPG", "Open World", "Fantasy"],
    developer: "CD PROJEKT RED",
    publisher: "CD PROJEKT RED",
    releaseDate: "2015-05-18",
    reviewScore: 96,
    basePrice: 149.99,
    currentPrice: 29.99,
    historicalLow: 19.99,
    currentPlayers: 21400,
    trendFactor: 0.96,
    stores: [
      { storeName: "Steam", price: 29.99, discountPercent: 80, drm: "Steam", isOfficial: true },
      { storeName: "GOG.com", price: 27.99, discountPercent: 81, drm: "DRM-free", isOfficial: true },
      { storeName: "Epic Games Store", price: 34.99, discountPercent: 77, drm: "Epic" }
    ]
  },
  {
    id: "baldurs-gate-3",
    steamAppId: 1086940,
    title: "Baldur's Gate 3",
    slug: "baldurs-gate-3",
    platform: "PC",
    description:
      "Party-based RPG built around choice, tactical combat and cooperative campaign play.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/1086940/header.jpg",
    genres: ["RPG", "Turn-Based", "Co-op"],
    developer: "Larian Studios",
    publisher: "Larian Studios",
    releaseDate: "2023-08-03",
    reviewScore: 96,
    basePrice: 249.99,
    currentPrice: 199.99,
    historicalLow: 159.99,
    currentPlayers: 86100,
    trendFactor: 1.02,
    stores: [
      { storeName: "Steam", price: 199.99, discountPercent: 20, drm: "Steam", isOfficial: true },
      { storeName: "GOG.com", price: 199.99, discountPercent: 20, drm: "DRM-free", isOfficial: true }
    ]
  },
  {
    id: "elden-ring",
    steamAppId: 1245620,
    title: "Elden Ring",
    slug: "elden-ring",
    platform: "PC",
    description:
      "Action RPG focused on exploration, boss encounters and build experimentation in a dark fantasy world.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/1245620/header.jpg",
    genres: ["Action RPG", "Soulslike", "Open World"],
    developer: "FromSoftware",
    publisher: "Bandai Namco Entertainment",
    releaseDate: "2022-02-25",
    reviewScore: 92,
    basePrice: 249.99,
    currentPrice: 169.99,
    historicalLow: 129.99,
    currentPlayers: 55800,
    trendFactor: 1.07,
    stores: [
      { storeName: "Steam", price: 169.99, discountPercent: 32, drm: "Steam", isOfficial: true },
      { storeName: "Green Man Gaming", price: 164.99, discountPercent: 34, drm: "Steam" }
    ]
  },
  {
    id: "stardew-valley",
    steamAppId: 413150,
    title: "Stardew Valley",
    slug: "stardew-valley",
    platform: "PC",
    description:
      "Farming and life simulation game with cooperative play, crafting and strong replay value.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/413150/header.jpg",
    genres: ["Simulation", "Farming", "Cozy"],
    developer: "ConcernedApe",
    publisher: "ConcernedApe",
    releaseDate: "2016-02-26",
    reviewScore: 98,
    basePrice: 53.99,
    currentPrice: 23.99,
    historicalLow: 17.99,
    currentPlayers: 38900,
    trendFactor: 1.18,
    stores: [
      { storeName: "Steam", price: 23.99, discountPercent: 56, drm: "Steam", isOfficial: true },
      { storeName: "Humble Store", price: 21.99, discountPercent: 59, drm: "Steam" },
      { storeName: "GOG.com", price: 24.99, discountPercent: 54, drm: "DRM-free", isOfficial: true }
    ]
  },
  {
    id: "terraria",
    steamAppId: 105600,
    title: "Terraria",
    slug: "terraria",
    platform: "PC",
    description:
      "2D sandbox adventure with crafting, exploration, boss progression and long-term content updates.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/105600/header.jpg",
    genres: ["Sandbox", "Adventure", "Survival"],
    developer: "Re-Logic",
    publisher: "Re-Logic",
    releaseDate: "2011-05-16",
    reviewScore: 97,
    basePrice: 39.99,
    currentPrice: 19.99,
    historicalLow: 9.99,
    currentPlayers: 52300,
    trendFactor: 1.03,
    stores: [
      { storeName: "Steam", price: 19.99, discountPercent: 50, drm: "Steam", isOfficial: true },
      { storeName: "GOG.com", price: 19.99, discountPercent: 50, drm: "DRM-free", isOfficial: true }
    ]
  },
  {
    id: "euro-truck-simulator-2",
    steamAppId: 227300,
    title: "Euro Truck Simulator 2",
    slug: "euro-truck-simulator-2",
    platform: "PC",
    description:
      "Driving simulation game with a stable community, economy loops and extensive map expansions.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/227300/header.jpg",
    genres: ["Simulation", "Driving", "Management"],
    developer: "SCS Software",
    publisher: "SCS Software",
    releaseDate: "2012-10-18",
    reviewScore: 95,
    basePrice: 89.99,
    currentPrice: 17.99,
    historicalLow: 9.99,
    currentPlayers: 42100,
    trendFactor: 0.98,
    stores: [
      { storeName: "Steam", price: 17.99, discountPercent: 80, drm: "Steam", isOfficial: true },
      { storeName: "Humble Store", price: 19.99, discountPercent: 78, drm: "Steam" }
    ]
  },
  {
    id: "dota-2",
    steamAppId: 570,
    title: "Dota 2",
    slug: "dota-2",
    platform: "Steam",
    description: "Competitive MOBA with one of the largest long-running player communities on Steam.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/570/header.jpg",
    genres: ["MOBA", "Competitive", "Strategy", "Multiplayer"],
    developer: "Valve",
    publisher: "Valve",
    releaseDate: "2013-07-09",
    reviewScore: 82,
    basePrice: 0,
    currentPrice: 0,
    historicalLow: 0,
    currentPlayers: 512000,
    trendFactor: 1.02,
    stores: [{ storeName: "Steam", price: 0, discountPercent: 0, drm: "Steam", isOfficial: true }]
  },
  {
    id: "pubg-battlegrounds",
    steamAppId: 578080,
    title: "PUBG: Battlegrounds",
    slug: "pubg-battlegrounds",
    platform: "Steam",
    description: "Large-scale battle royale shooter with squad play and a very active global audience.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/578080/header.jpg",
    genres: ["Battle Royale", "Shooter", "Multiplayer"],
    developer: "KRAFTON",
    publisher: "KRAFTON",
    releaseDate: "2017-12-21",
    reviewScore: 72,
    basePrice: 0,
    currentPrice: 0,
    historicalLow: 0,
    currentPlayers: 438000,
    trendFactor: 0.97,
    stores: [{ storeName: "Steam", price: 0, discountPercent: 0, drm: "Steam", isOfficial: true }]
  },
  {
    id: "apex-legends",
    steamAppId: 1172470,
    title: "Apex Legends",
    slug: "apex-legends",
    platform: "Steam",
    description: "Fast hero-based battle royale focused on squad tactics and seasonal updates.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/1172470/header.jpg",
    genres: ["Battle Royale", "FPS", "Multiplayer"],
    developer: "Respawn Entertainment",
    publisher: "Electronic Arts",
    releaseDate: "2020-11-04",
    reviewScore: 76,
    basePrice: 0,
    currentPrice: 0,
    historicalLow: 0,
    currentPlayers: 118000,
    trendFactor: 0.93,
    stores: [{ storeName: "Steam", price: 0, discountPercent: 0, drm: "Steam", isOfficial: true }]
  },
  {
    id: "grand-theft-auto-v",
    steamAppId: 271590,
    title: "Grand Theft Auto V",
    slug: "grand-theft-auto-v",
    platform: "PC",
    description: "Open-world action game with a long-running online mode and regular player spikes.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/271590/header.jpg",
    genres: ["Open World", "Action", "Multiplayer"],
    developer: "Rockstar North",
    publisher: "Rockstar Games",
    releaseDate: "2015-04-14",
    reviewScore: 87,
    basePrice: 129.99,
    currentPrice: 64.99,
    historicalLow: 39.99,
    currentPlayers: 126000,
    trendFactor: 1.04,
    stores: [{ storeName: "Steam", price: 64.99, discountPercent: 50, drm: "Steam", isOfficial: true }]
  },
  {
    id: "rust",
    steamAppId: 252490,
    title: "Rust",
    slug: "rust",
    platform: "PC",
    description: "Hardcore multiplayer survival sandbox with strong social and server-driven retention.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/252490/header.jpg",
    genres: ["Survival", "Sandbox", "Multiplayer"],
    developer: "Facepunch Studios",
    publisher: "Facepunch Studios",
    releaseDate: "2018-02-08",
    reviewScore: 87,
    basePrice: 174.99,
    currentPrice: 104.99,
    historicalLow: 69.99,
    currentPlayers: 98000,
    trendFactor: 1.09,
    stores: [{ storeName: "Steam", price: 104.99, discountPercent: 40, drm: "Steam", isOfficial: true }]
  },
  {
    id: "team-fortress-2",
    steamAppId: 440,
    title: "Team Fortress 2",
    slug: "team-fortress-2",
    platform: "Steam",
    description: "Class-based team shooter with a persistent community and free-to-play access.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/440/header.jpg",
    genres: ["FPS", "Team-Based", "Multiplayer"],
    developer: "Valve",
    publisher: "Valve",
    releaseDate: "2007-10-10",
    reviewScore: 93,
    basePrice: 0,
    currentPrice: 0,
    historicalLow: 0,
    currentPlayers: 76000,
    trendFactor: 1.01,
    stores: [{ storeName: "Steam", price: 0, discountPercent: 0, drm: "Steam", isOfficial: true }]
  },
  {
    id: "warframe",
    steamAppId: 230410,
    title: "Warframe",
    slug: "warframe",
    platform: "Steam",
    description: "Free-to-play cooperative action RPG with years of content and steady player activity.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/230410/header.jpg",
    genres: ["Action RPG", "Co-op", "Free to Play"],
    developer: "Digital Extremes",
    publisher: "Digital Extremes",
    releaseDate: "2013-03-25",
    reviewScore: 86,
    basePrice: 0,
    currentPrice: 0,
    historicalLow: 0,
    currentPlayers: 72000,
    trendFactor: 1.12,
    stores: [{ storeName: "Steam", price: 0, discountPercent: 0, drm: "Steam", isOfficial: true }]
  },
  {
    id: "destiny-2",
    steamAppId: 1085660,
    title: "Destiny 2",
    slug: "destiny-2",
    platform: "Steam",
    description: "Online looter shooter with cooperative raids, PvP and expansion-driven player cycles.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/1085660/header.jpg",
    genres: ["FPS", "Looter Shooter", "Co-op"],
    developer: "Bungie",
    publisher: "Bungie",
    releaseDate: "2019-10-01",
    reviewScore: 78,
    basePrice: 0,
    currentPrice: 0,
    historicalLow: 0,
    currentPlayers: 64000,
    trendFactor: 0.88,
    stores: [{ storeName: "Steam", price: 0, discountPercent: 0, drm: "Steam", isOfficial: true }]
  },
  {
    id: "rimworld",
    steamAppId: 294100,
    title: "RimWorld",
    slug: "rimworld",
    platform: "PC",
    description: "Colony sim driven by emergent stories, mod support and deep management systems.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/294100/header.jpg",
    genres: ["Colony Sim", "Strategy", "Indie"],
    developer: "Ludeon Studios",
    publisher: "Ludeon Studios",
    releaseDate: "2018-10-17",
    reviewScore: 98,
    basePrice: 139.99,
    currentPrice: 111.99,
    historicalLow: 89.99,
    currentPlayers: 39200,
    trendFactor: 1.06,
    stores: [{ storeName: "Steam", price: 111.99, discountPercent: 20, drm: "Steam", isOfficial: true }]
  },
  {
    id: "project-zomboid",
    steamAppId: 108600,
    title: "Project Zomboid",
    slug: "project-zomboid",
    platform: "PC",
    description: "Open-ended zombie survival sim with deep systems and strong multiplayer servers.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/108600/header.jpg",
    genres: ["Survival", "Simulation", "Co-op"],
    developer: "The Indie Stone",
    publisher: "The Indie Stone",
    releaseDate: "2013-11-08",
    reviewScore: 94,
    basePrice: 79.99,
    currentPrice: 53.99,
    historicalLow: 39.99,
    currentPlayers: 36300,
    trendFactor: 1.15,
    stores: [{ storeName: "Steam", price: 53.99, discountPercent: 33, drm: "Steam", isOfficial: true }]
  },
  {
    id: "valheim",
    steamAppId: 892970,
    title: "Valheim",
    slug: "valheim",
    platform: "PC",
    description: "Cooperative Viking survival game with exploration, building and boss progression.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/892970/header.jpg",
    genres: ["Survival", "Co-op", "Open World", "Indie"],
    developer: "Iron Gate AB",
    publisher: "Coffee Stain Publishing",
    releaseDate: "2021-02-02",
    reviewScore: 94,
    basePrice: 89.99,
    currentPrice: 44.99,
    historicalLow: 34.99,
    currentPlayers: 31500,
    trendFactor: 1.22,
    stores: [{ storeName: "Steam", price: 44.99, discountPercent: 50, drm: "Steam", isOfficial: true }]
  },
  {
    id: "no-mans-sky",
    steamAppId: 275850,
    title: "No Man's Sky",
    slug: "no-mans-sky",
    platform: "PC",
    description: "Space exploration sandbox with frequent updates and broad cooperative discovery.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/275850/header.jpg",
    genres: ["Exploration", "Survival", "Co-op"],
    developer: "Hello Games",
    publisher: "Hello Games",
    releaseDate: "2016-08-12",
    reviewScore: 80,
    basePrice: 249.99,
    currentPrice: 99.99,
    historicalLow: 79.99,
    currentPlayers: 28900,
    trendFactor: 1.27,
    stores: [{ storeName: "Steam", price: 99.99, discountPercent: 60, drm: "Steam", isOfficial: true }]
  },
  {
    id: "ark-survival-ascended",
    steamAppId: 2399830,
    title: "ARK: Survival Ascended",
    slug: "ark-survival-ascended",
    platform: "PC",
    description: "Dinosaur survival remake with persistent servers, crafting and tribe-based play.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/2399830/header.jpg",
    genres: ["Survival", "Open World", "Multiplayer"],
    developer: "Studio Wildcard",
    publisher: "Studio Wildcard",
    releaseDate: "2023-10-25",
    reviewScore: 58,
    basePrice: 199.99,
    currentPrice: 139.99,
    historicalLow: 119.99,
    currentPlayers: 41200,
    trendFactor: 0.91,
    stores: [{ storeName: "Steam", price: 139.99, discountPercent: 30, drm: "Steam", isOfficial: true }]
  },
  {
    id: "football-manager-2024",
    steamAppId: 2252570,
    title: "Football Manager 2024",
    slug: "football-manager-2024",
    platform: "PC",
    description: "Football management sim with deep data, long saves and strong seasonal engagement.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/2252570/header.jpg",
    genres: ["Sports", "Simulation", "Management"],
    developer: "Sports Interactive",
    publisher: "SEGA",
    releaseDate: "2023-11-06",
    reviewScore: 87,
    basePrice: 229.99,
    currentPrice: 91.99,
    historicalLow: 79.99,
    currentPlayers: 74200,
    trendFactor: 1.03,
    stores: [{ storeName: "Steam", price: 91.99, discountPercent: 60, drm: "Steam", isOfficial: true }]
  },
  {
    id: "path-of-exile",
    steamAppId: 238960,
    title: "Path of Exile",
    slug: "path-of-exile",
    platform: "Steam",
    description: "Deep free-to-play action RPG with seasonal leagues and a complex economy.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/238960/header.jpg",
    genres: ["Action RPG", "Free to Play", "Multiplayer"],
    developer: "Grinding Gear Games",
    publisher: "Grinding Gear Games",
    releaseDate: "2013-10-23",
    reviewScore: 88,
    basePrice: 0,
    currentPrice: 0,
    historicalLow: 0,
    currentPlayers: 69000,
    trendFactor: 1.31,
    stores: [{ storeName: "Steam", price: 0, discountPercent: 0, drm: "Steam", isOfficial: true }]
  },
  {
    id: "war-thunder",
    steamAppId: 236390,
    title: "War Thunder",
    slug: "war-thunder",
    platform: "Steam",
    description: "Vehicle combat MMO with aircraft, tanks and naval battles across many eras.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/236390/header.jpg",
    genres: ["Simulation", "Action", "Multiplayer"],
    developer: "Gaijin Entertainment",
    publisher: "Gaijin Entertainment",
    releaseDate: "2013-08-15",
    reviewScore: 74,
    basePrice: 0,
    currentPrice: 0,
    historicalLow: 0,
    currentPlayers: 103000,
    trendFactor: 1.05,
    stores: [{ storeName: "Steam", price: 0, discountPercent: 0, drm: "Steam", isOfficial: true }]
  },
  {
    id: "dead-by-daylight",
    steamAppId: 381210,
    title: "Dead by Daylight",
    slug: "dead-by-daylight",
    platform: "PC",
    description: "Asymmetric multiplayer horror with licensed characters and frequent live updates.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/381210/header.jpg",
    genres: ["Horror", "Multiplayer", "Co-op"],
    developer: "Behaviour Interactive",
    publisher: "Behaviour Interactive",
    releaseDate: "2016-06-14",
    reviewScore: 79,
    basePrice: 89.99,
    currentPrice: 35.99,
    historicalLow: 24.99,
    currentPlayers: 51500,
    trendFactor: 1.13,
    stores: [{ storeName: "Steam", price: 35.99, discountPercent: 60, drm: "Steam", isOfficial: true }]
  },
  {
    id: "monster-hunter-world",
    steamAppId: 582010,
    title: "Monster Hunter: World",
    slug: "monster-hunter-world",
    platform: "PC",
    description: "Cooperative action RPG about hunting large monsters and crafting gear from them.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/582010/header.jpg",
    genres: ["Action RPG", "Co-op", "Adventure"],
    developer: "CAPCOM",
    publisher: "CAPCOM",
    releaseDate: "2018-08-09",
    reviewScore: 89,
    basePrice: 119.99,
    currentPrice: 39.99,
    historicalLow: 29.99,
    currentPlayers: 44500,
    trendFactor: 1.18,
    stores: [{ storeName: "Steam", price: 39.99, discountPercent: 67, drm: "Steam", isOfficial: true }]
  },
  {
    id: "civilization-vi",
    steamAppId: 289070,
    title: "Sid Meier's Civilization VI",
    slug: "civilization-vi",
    platform: "PC",
    description: "Turn-based 4X strategy game with long campaigns, expansions and strong replayability.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/289070/header.jpg",
    genres: ["Strategy", "4X", "Turn-Based"],
    developer: "Firaxis Games",
    publisher: "2K",
    releaseDate: "2016-10-20",
    reviewScore: 86,
    basePrice: 249.99,
    currentPrice: 24.99,
    historicalLow: 19.99,
    currentPlayers: 57800,
    trendFactor: 1.00,
    stores: [{ storeName: "Steam", price: 24.99, discountPercent: 90, drm: "Steam", isOfficial: true }]
  },
  {
    id: "cities-skylines",
    steamAppId: 255710,
    title: "Cities: Skylines",
    slug: "cities-skylines",
    platform: "PC",
    description: "City-building simulation with extensive DLC, mod support and management depth.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/255710/header.jpg",
    genres: ["Simulation", "City Builder", "Strategy"],
    developer: "Colossal Order",
    publisher: "Paradox Interactive",
    releaseDate: "2015-03-10",
    reviewScore: 93,
    basePrice: 119.99,
    currentPrice: 29.99,
    historicalLow: 19.99,
    currentPlayers: 18500,
    trendFactor: 0.96,
    stores: [{ storeName: "Steam", price: 29.99, discountPercent: 75, drm: "Steam", isOfficial: true }]
  },
  {
    id: "factorio",
    steamAppId: 427520,
    title: "Factorio",
    slug: "factorio",
    platform: "PC",
    description: "Factory automation strategy sandbox with complex logistics and deep optimization.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/427520/header.jpg",
    genres: ["Automation", "Strategy", "Simulation", "Indie"],
    developer: "Wube Software",
    publisher: "Wube Software",
    releaseDate: "2020-08-14",
    reviewScore: 97,
    basePrice: 150,
    currentPrice: 150,
    historicalLow: 120,
    currentPlayers: 34500,
    trendFactor: 1.07,
    stores: [{ storeName: "Steam", price: 150, discountPercent: 0, drm: "Steam", isOfficial: true }]
  },
  {
    id: "satisfactory",
    steamAppId: 526870,
    title: "Satisfactory",
    slug: "satisfactory",
    platform: "PC",
    description: "First-person factory building game with exploration, automation and cooperative play.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/526870/header.jpg",
    genres: ["Automation", "Open World", "Co-op", "Indie"],
    developer: "Coffee Stain Studios",
    publisher: "Coffee Stain Publishing",
    releaseDate: "2020-06-08",
    reviewScore: 97,
    basePrice: 179.99,
    currentPrice: 89.99,
    historicalLow: 69.99,
    currentPlayers: 29200,
    trendFactor: 1.24,
    stores: [{ storeName: "Steam", price: 89.99, discountPercent: 50, drm: "Steam", isOfficial: true }]
  },
  {
    id: "palworld",
    steamAppId: 1623730,
    title: "Palworld",
    slug: "palworld",
    platform: "PC",
    description: "Creature-collecting survival game with base building, crafting and multiplayer servers.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/1623730/header.jpg",
    genres: ["Survival", "Open World", "Co-op"],
    developer: "Pocketpair",
    publisher: "Pocketpair",
    releaseDate: "2024-01-19",
    reviewScore: 93,
    basePrice: 129.99,
    currentPrice: 97.49,
    historicalLow: 84.49,
    currentPlayers: 68400,
    trendFactor: 0.84,
    stores: [{ storeName: "Steam", price: 97.49, discountPercent: 25, drm: "Steam", isOfficial: true }]
  },
  {
    id: "helldivers-2",
    steamAppId: 553850,
    title: "HELLDIVERS 2",
    slug: "helldivers-2",
    platform: "PC",
    description: "Cooperative third-person shooter built around squad objectives and global war progress.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/553850/header.jpg",
    genres: ["Co-op", "Shooter", "Action"],
    developer: "Arrowhead Game Studios",
    publisher: "PlayStation PC LLC",
    releaseDate: "2024-02-08",
    reviewScore: 83,
    basePrice: 169.99,
    currentPrice: 135.99,
    historicalLow: 119.99,
    currentPlayers: 52700,
    trendFactor: 0.79,
    stores: [{ storeName: "Steam", price: 135.99, discountPercent: 20, drm: "Steam", isOfficial: true }]
  },
  {
    id: "the-finals",
    steamAppId: 2073850,
    title: "THE FINALS",
    slug: "the-finals",
    platform: "Steam",
    description: "Free-to-play arena shooter with destructible maps and objective-focused team play.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/2073850/header.jpg",
    genres: ["FPS", "Multiplayer", "Free to Play"],
    developer: "Embark Studios",
    publisher: "Embark Studios",
    releaseDate: "2023-12-07",
    reviewScore: 74,
    basePrice: 0,
    currentPrice: 0,
    historicalLow: 0,
    currentPlayers: 33200,
    trendFactor: 1.19,
    stores: [{ storeName: "Steam", price: 0, discountPercent: 0, drm: "Steam", isOfficial: true }]
  },
  {
    id: "hades",
    steamAppId: 1145360,
    title: "Hades",
    slug: "hades",
    platform: "PC",
    description: "Action roguelike with sharp combat, progression and highly replayable runs.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/1145360/header.jpg",
    genres: ["Roguelike", "Action", "Indie"],
    developer: "Supergiant Games",
    publisher: "Supergiant Games",
    releaseDate: "2020-09-17",
    reviewScore: 98,
    basePrice: 109.99,
    currentPrice: 43.99,
    historicalLow: 35.99,
    currentPlayers: 16700,
    trendFactor: 1.16,
    stores: [{ storeName: "Steam", price: 43.99, discountPercent: 60, drm: "Steam", isOfficial: true }]
  },
  {
    id: "hollow-knight",
    steamAppId: 367520,
    title: "Hollow Knight",
    slug: "hollow-knight",
    platform: "PC",
    description: "Atmospheric metroidvania with precise combat, exploration and strong indie value.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/367520/header.jpg",
    genres: ["Metroidvania", "Indie", "Action"],
    developer: "Team Cherry",
    publisher: "Team Cherry",
    releaseDate: "2017-02-24",
    reviewScore: 97,
    basePrice: 53.99,
    currentPrice: 26.99,
    historicalLow: 17.99,
    currentPlayers: 14200,
    trendFactor: 1.08,
    stores: [{ storeName: "Steam", price: 26.99, discountPercent: 50, drm: "Steam", isOfficial: true }]
  },
  {
    id: "slay-the-spire",
    steamAppId: 646570,
    title: "Slay the Spire",
    slug: "slay-the-spire",
    platform: "PC",
    description: "Deckbuilding roguelike with daily runs, crisp systems and excellent replay value.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/646570/header.jpg",
    genres: ["Card Game", "Roguelike", "Indie", "Strategy"],
    developer: "Mega Crit",
    publisher: "Mega Crit",
    releaseDate: "2019-01-23",
    reviewScore: 97,
    basePrice: 99.99,
    currentPrice: 31.99,
    historicalLow: 24.99,
    currentPlayers: 18800,
    trendFactor: 1.03,
    stores: [{ storeName: "Steam", price: 31.99, discountPercent: 68, drm: "Steam", isOfficial: true }]
  },
  {
    id: "risk-of-rain-2",
    steamAppId: 632360,
    title: "Risk of Rain 2",
    slug: "risk-of-rain-2",
    platform: "PC",
    description: "Cooperative roguelike shooter with scaling chaos, unlocks and run variety.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/632360/header.jpg",
    genres: ["Roguelike", "Co-op", "Shooter", "Indie"],
    developer: "Hopoo Games",
    publisher: "Gearbox Publishing",
    releaseDate: "2020-08-11",
    reviewScore: 94,
    basePrice: 109.99,
    currentPrice: 54.99,
    historicalLow: 35.99,
    currentPlayers: 13600,
    trendFactor: 0.98,
    stores: [{ storeName: "Steam", price: 54.99, discountPercent: 50, drm: "Steam", isOfficial: true }]
  },
  {
    id: "deep-rock-galactic",
    steamAppId: 548430,
    title: "Deep Rock Galactic",
    slug: "deep-rock-galactic",
    platform: "PC",
    description: "Cooperative mining shooter with class roles, procedural caves and friendly community play.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/548430/header.jpg",
    genres: ["Co-op", "FPS", "Indie"],
    developer: "Ghost Ship Games",
    publisher: "Coffee Stain Publishing",
    releaseDate: "2020-05-13",
    reviewScore: 97,
    basePrice: 119.99,
    currentPrice: 39.99,
    historicalLow: 29.99,
    currentPlayers: 24800,
    trendFactor: 1.10,
    stores: [{ storeName: "Steam", price: 39.99, discountPercent: 67, drm: "Steam", isOfficial: true }]
  },
  {
    id: "red-dead-redemption-2",
    steamAppId: 1174180,
    title: "Red Dead Redemption 2",
    slug: "red-dead-redemption-2",
    platform: "PC",
    description: "Cinematic open-world western with a large single-player campaign and online component.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/1174180/header.jpg",
    genres: ["Open World", "Action", "Adventure"],
    developer: "Rockstar Games",
    publisher: "Rockstar Games",
    releaseDate: "2019-12-05",
    reviewScore: 91,
    basePrice: 249.99,
    currentPrice: 82.49,
    historicalLow: 69.99,
    currentPlayers: 61100,
    trendFactor: 1.04,
    stores: [{ storeName: "Steam", price: 82.49, discountPercent: 67, drm: "Steam", isOfficial: true }]
  },
  {
    id: "forza-horizon-5",
    steamAppId: 1551360,
    title: "Forza Horizon 5",
    slug: "forza-horizon-5",
    platform: "PC",
    description: "Open-world racing game with seasonal events, car collecting and social challenges.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/1551360/header.jpg",
    genres: ["Racing", "Open World", "Multiplayer"],
    developer: "Playground Games",
    publisher: "Xbox Game Studios",
    releaseDate: "2021-11-08",
    reviewScore: 88,
    basePrice: 249.99,
    currentPrice: 124.99,
    historicalLow: 99.99,
    currentPlayers: 25500,
    trendFactor: 1.00,
    stores: [{ storeName: "Steam", price: 124.99, discountPercent: 50, drm: "Steam", isOfficial: true }]
  },
  {
    id: "sea-of-thieves",
    steamAppId: 1172620,
    title: "Sea of Thieves",
    slug: "sea-of-thieves",
    platform: "PC",
    description: "Cooperative pirate sandbox with emergent multiplayer encounters and seasonal events.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/1172620/header.jpg",
    genres: ["Adventure", "Co-op", "Open World", "Multiplayer"],
    developer: "Rare Ltd",
    publisher: "Xbox Game Studios",
    releaseDate: "2020-06-03",
    reviewScore: 90,
    basePrice: 179.99,
    currentPrice: 71.99,
    historicalLow: 59.99,
    currentPlayers: 30200,
    trendFactor: 1.21,
    stores: [{ storeName: "Steam", price: 71.99, discountPercent: 60, drm: "Steam", isOfficial: true }]
  },
  {
    id: "phasmophobia",
    steamAppId: 739630,
    title: "Phasmophobia",
    slug: "phasmophobia",
    platform: "PC",
    description: "Cooperative ghost investigation horror game with voice interaction and tense runs.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/739630/header.jpg",
    genres: ["Horror", "Co-op", "Indie"],
    developer: "Kinetic Games",
    publisher: "Kinetic Games",
    releaseDate: "2020-09-18",
    reviewScore: 96,
    basePrice: 64.99,
    currentPrice: 45.49,
    historicalLow: 39.99,
    currentPlayers: 22400,
    trendFactor: 1.18,
    stores: [{ storeName: "Steam", price: 45.49, discountPercent: 30, drm: "Steam", isOfficial: true }]
  },
  {
    id: "lethal-company",
    steamAppId: 1966720,
    title: "Lethal Company",
    slug: "lethal-company",
    platform: "PC",
    description: "Cooperative horror extraction game where simple systems produce memorable squad stories.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/1966720/header.jpg",
    genres: ["Horror", "Co-op", "Indie"],
    developer: "Zeekerss",
    publisher: "Zeekerss",
    releaseDate: "2023-10-23",
    reviewScore: 97,
    basePrice: 44.99,
    currentPrice: 35.99,
    historicalLow: 31.99,
    currentPlayers: 35800,
    trendFactor: 0.86,
    stores: [{ storeName: "Steam", price: 35.99, discountPercent: 20, drm: "Steam", isOfficial: true }]
  },
  {
    id: "dont-starve-together",
    steamAppId: 322330,
    title: "Don't Starve Together",
    slug: "dont-starve-together",
    platform: "PC",
    description: "Cooperative survival game with stylized danger, crafting and seasonal content.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/322330/header.jpg",
    genres: ["Survival", "Co-op", "Indie"],
    developer: "Klei Entertainment",
    publisher: "Klei Entertainment",
    releaseDate: "2016-04-21",
    reviewScore: 95,
    basePrice: 53.99,
    currentPrice: 17.99,
    historicalLow: 11.99,
    currentPlayers: 33100,
    trendFactor: 1.09,
    stores: [{ storeName: "Steam", price: 17.99, discountPercent: 67, drm: "Steam", isOfficial: true }]
  },
  {
    id: "left-4-dead-2",
    steamAppId: 550,
    title: "Left 4 Dead 2",
    slug: "left-4-dead-2",
    platform: "PC",
    description: "Classic cooperative zombie shooter with campaigns, versus play and enduring mods.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/550/header.jpg",
    genres: ["Co-op", "FPS", "Horror"],
    developer: "Valve",
    publisher: "Valve",
    releaseDate: "2009-11-17",
    reviewScore: 97,
    basePrice: 39.99,
    currentPrice: 3.99,
    historicalLow: 3.99,
    currentPlayers: 27600,
    trendFactor: 1.06,
    stores: [{ storeName: "Steam", price: 3.99, discountPercent: 90, drm: "Steam", isOfficial: true }]
  },
  {
    id: "payday-2",
    steamAppId: 218620,
    title: "PAYDAY 2",
    slug: "payday-2",
    platform: "PC",
    description: "Cooperative heist shooter with many missions, builds and an enormous DLC catalog.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/218620/header.jpg",
    genres: ["Co-op", "FPS", "Action"],
    developer: "OVERKILL",
    publisher: "Starbreeze Publishing",
    releaseDate: "2013-08-13",
    reviewScore: 89,
    basePrice: 39.99,
    currentPrice: 7.99,
    historicalLow: 3.99,
    currentPlayers: 24700,
    trendFactor: 0.95,
    stores: [{ storeName: "Steam", price: 7.99, discountPercent: 80, drm: "Steam", isOfficial: true }]
  },
  {
    id: "rocket-league",
    steamAppId: 252950,
    title: "Rocket League",
    slug: "rocket-league",
    platform: "PC",
    description: "Car football arcade game represented here with historical/mock Steam activity.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/252950/header.jpg",
    genres: ["Sports", "Racing", "Multiplayer"],
    developer: "Psyonix",
    publisher: "Psyonix",
    releaseDate: "2015-07-07",
    reviewScore: 91,
    basePrice: 0,
    currentPrice: 0,
    historicalLow: 0,
    currentPlayers: 59300,
    trendFactor: 1.02,
    stores: [{ storeName: "Steam", price: 0, discountPercent: 0, drm: "Steam", isOfficial: true }]
  },
  {
    id: "mount-and-blade-ii-bannerlord",
    steamAppId: 261550,
    title: "Mount & Blade II: Bannerlord",
    slug: "mount-and-blade-ii-bannerlord",
    platform: "PC",
    description: "Medieval sandbox RPG with large battles, kingdom management and mod potential.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/261550/header.jpg",
    genres: ["RPG", "Strategy", "Sandbox"],
    developer: "TaleWorlds Entertainment",
    publisher: "TaleWorlds Entertainment",
    releaseDate: "2022-10-25",
    reviewScore: 87,
    basePrice: 229.99,
    currentPrice: 114.99,
    historicalLow: 91.99,
    currentPlayers: 21800,
    trendFactor: 1.05,
    stores: [{ storeName: "Steam", price: 114.99, discountPercent: 50, drm: "Steam", isOfficial: true }]
  },
  {
    id: "total-war-warhammer-iii",
    steamAppId: 1142710,
    title: "Total War: Warhammer III",
    slug: "total-war-warhammer-iii",
    platform: "PC",
    description: "Grand strategy and real-time battles set in the Warhammer fantasy universe.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/1142710/header.jpg",
    genres: ["Strategy", "Grand Strategy", "Fantasy"],
    developer: "Creative Assembly",
    publisher: "SEGA",
    releaseDate: "2022-02-17",
    reviewScore: 75,
    basePrice: 249.99,
    currentPrice: 124.99,
    historicalLow: 99.99,
    currentPlayers: 34200,
    trendFactor: 1.17,
    stores: [{ storeName: "Steam", price: 124.99, discountPercent: 50, drm: "Steam", isOfficial: true }]
  },
  {
    id: "crusader-kings-iii",
    steamAppId: 1158310,
    title: "Crusader Kings III",
    slug: "crusader-kings-iii",
    platform: "PC",
    description: "Dynasty-driven grand strategy game focused on politics, succession and roleplay.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/1158310/header.jpg",
    genres: ["Grand Strategy", "Strategy", "Simulation"],
    developer: "Paradox Development Studio",
    publisher: "Paradox Interactive",
    releaseDate: "2020-09-01",
    reviewScore: 91,
    basePrice: 199.99,
    currentPrice: 79.99,
    historicalLow: 59.99,
    currentPlayers: 28700,
    trendFactor: 1.11,
    stores: [{ storeName: "Steam", price: 79.99, discountPercent: 60, drm: "Steam", isOfficial: true }]
  },
  {
    id: "hearts-of-iron-iv",
    steamAppId: 394360,
    title: "Hearts of Iron IV",
    slug: "hearts-of-iron-iv",
    platform: "PC",
    description: "World War II grand strategy sandbox with deep production, diplomacy and warfare.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/394360/header.jpg",
    genres: ["Grand Strategy", "Strategy", "Simulation"],
    developer: "Paradox Development Studio",
    publisher: "Paradox Interactive",
    releaseDate: "2016-06-06",
    reviewScore: 90,
    basePrice: 179.99,
    currentPrice: 44.99,
    historicalLow: 35.99,
    currentPlayers: 45800,
    trendFactor: 1.04,
    stores: [{ storeName: "Steam", price: 44.99, discountPercent: 75, drm: "Steam", isOfficial: true }]
  },
  {
    id: "europa-universalis-iv",
    steamAppId: 236850,
    title: "Europa Universalis IV",
    slug: "europa-universalis-iv",
    platform: "PC",
    description: "Historical grand strategy game with diplomacy, trade and centuries-long campaigns.",
    coverUrl: "https://cdn.akamai.steamstatic.com/steam/apps/236850/header.jpg",
    genres: ["Grand Strategy", "Strategy", "Simulation"],
    developer: "Paradox Development Studio",
    publisher: "Paradox Interactive",
    releaseDate: "2013-08-13",
    reviewScore: 87,
    basePrice: 179.99,
    currentPrice: 35.99,
    historicalLow: 26.99,
    currentPlayers: 20900,
    trendFactor: 0.99,
    stores: [{ storeName: "Steam", price: 35.99, discountPercent: 80, drm: "Steam", isOfficial: true }]
  }
];

export const mockGameCatalog: GameImportInput[] = fixtures.map(({ stores: _stores, ...fixture }) => ({
  ...fixture,
  source: "mock"
}));

function priceForDay(fixture: GameFixture, dayOffset: number): number {
  if (fixture.currentPrice === 0) {
    return 0;
  }

  const wave = Math.sin(dayOffset * 0.9) * 0.035;
  const olderPremium = dayOffset * 0.014;
  const price = fixture.currentPrice * (1 + olderPremium + wave);
  return Math.max(fixture.historicalLow, Number(price.toFixed(2)));
}

function playersForDay(fixture: GameFixture, dayOffset: number): number {
  const trendDelta = fixture.trendFactor - 1;
  const historicalFactor = 1 - trendDelta * (dayOffset / 13);
  const wave = Math.sin(dayOffset * 0.7 + fixture.steamAppId) * 0.055;
  return Math.max(0, Math.round(fixture.currentPlayers * (historicalFactor + wave)));
}

export const mockGames: Game[] = fixtures.map((fixture) => ({
  ...fixture,
  source: "mock",
  createdAt: daysAgo(30),
  updatedAt: baseDate
}));

export const mockStoreOffers: StoreOffer[] = fixtures.flatMap((fixture) =>
  fixture.stores.map((offer, index) => ({
    id: `offer-${fixture.id}-${index + 1}`,
    gameId: fixture.id,
    steamAppId: fixture.steamAppId,
    storeId: `store-${slugify(offer.storeName)}`,
    sourceId: "price-source-mock-seed",
    provider: "mock",
    storeName: offer.storeName,
    storeType: offer.isOfficial ? "official" : "unknown",
    title: fixture.title,
    price: offer.price,
    regularPrice: fixture.basePrice,
    historicalLow: fixture.historicalLow,
    currency: "PLN",
    discountPercent: offer.discountPercent,
    url:
      offer.storeName === "Steam"
        ? `https://store.steampowered.com/app/${fixture.steamAppId}`
        : "https://example.com/gamevalue-demo-offer",
    externalUrl:
      offer.storeName === "Steam"
        ? `https://store.steampowered.com/app/${fixture.steamAppId}`
        : "https://example.com/gamevalue-demo-offer",
    region: "PL",
    isOfficial: offer.isOfficial ?? false,
    isOfficialStore: offer.isOfficial ?? false,
    isHistoricalLow: offer.price <= fixture.historicalLow,
    available: true,
    drm: offer.drm,
    platform: fixture.platform,
    sourceRawId: null,
    rawProviderData: null,
    fetchedAt: baseDate,
    createdAt: baseDate,
    updatedAt: baseDate,
    source: "mock",
    sourceConfidence: "internal-mock"
  }))
);

export const mockPriceSnapshots: GamePriceSnapshot[] = fixtures.flatMap((fixture) =>
  Array.from({ length: 14 }, (_, index) => {
    const dayOffset = 13 - index;
    const price = index === 13 ? fixture.currentPrice : priceForDay(fixture, dayOffset);
    return {
      id: `price-${fixture.id}-${index + 1}`,
      gameId: fixture.id,
      steamAppId: fixture.steamAppId,
      sourceId: "price-source-mock-seed",
      price,
      bestPrice: price,
      historicalLow: fixture.historicalLow,
      basePrice: fixture.basePrice,
      provider: "mock",
      storeType: fixture.stores[0]?.isOfficial ? "official" : "unknown",
      discountPercent:
        fixture.basePrice === 0 ? 0 : Math.max(0, Math.round((1 - price / fixture.basePrice) * 100)),
      storeName: fixture.stores[0]?.storeName ?? "Mock Store",
      currency: "PLN",
      externalUrl:
        fixture.stores[0]?.storeName === "Steam"
          ? `https://store.steampowered.com/app/${fixture.steamAppId}`
          : "https://example.com/gamevalue-demo-offer",
      offerCount: fixture.stores.length,
      isHistoricalLow: price <= fixture.historicalLow,
      sourceRawId: null,
      rawProviderData: null,
      fetchedAt: daysAgo(dayOffset),
      capturedAt: daysAgo(dayOffset),
      createdAt: daysAgo(dayOffset),
      source: "mock",
      sourceConfidence: "internal-mock"
    };
  })
);

function slugify(value: string): string {
  return (
    value
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 80) || "item"
  );
}

export const mockPlayerSnapshots: PlayerCountSnapshot[] = fixtures.flatMap((fixture) =>
  Array.from({ length: 14 }, (_, index) => {
    const dayOffset = 13 - index;
    const playersOnline = index === 13 ? fixture.currentPlayers : playersForDay(fixture, dayOffset);
    return {
      id: `players-${fixture.id}-${index + 1}`,
      gameId: fixture.id,
      steamAppId: fixture.steamAppId,
      playersOnline,
      capturedAt: daysAgo(dayOffset),
      source: "mock"
    };
  })
);

export const mockUsers: User[] = [
  {
    id: DEMO_USER_ID,
    email: "demo@gamevalueradar.local",
    name: "Demo user",
    createdAt: daysAgo(20)
  }
];

export const mockWatchlistItems: WatchlistItem[] = [
  {
    id: "watch-cyberpunk-2077",
    userId: DEMO_USER_ID,
    gameId: "cyberpunk-2077",
    targetPrice: 89.99,
    alertEnabled: true,
    createdAt: daysAgo(4)
  },
  {
    id: "watch-baldurs-gate-3",
    userId: DEMO_USER_ID,
    gameId: "baldurs-gate-3",
    targetPrice: 169.99,
    alertEnabled: true,
    createdAt: daysAgo(3)
  },
  {
    id: "watch-stardew-valley",
    userId: DEMO_USER_ID,
    gameId: "stardew-valley",
    targetPrice: 19.99,
    alertEnabled: false,
    createdAt: daysAgo(1)
  }
];

export const mockPriceAlerts: PriceAlert[] = [
  {
    id: "alert-cyberpunk-2077",
    userId: DEMO_USER_ID,
    gameId: "cyberpunk-2077",
    thresholdPrice: 89.99,
    isActive: true,
    triggeredAt: null,
    createdAt: daysAgo(4)
  },
  {
    id: "alert-baldurs-gate-3",
    userId: DEMO_USER_ID,
    gameId: "baldurs-gate-3",
    thresholdPrice: 169.99,
    isActive: true,
    triggeredAt: null,
    createdAt: daysAgo(3)
  }
];
